### ISSUE TITLE
Material Icons font not registering properly

### ISSUE THREAD

**Issue by indiesk** [0x73/SwiftIconFont#12]
Hi,

I love your library and I've been using it for almost all of my apps, but I've come across this error when using more than one Material Icons in one app.

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The operation couldn’t be completed. (com.apple.CoreText.CTFontManagerErrorDomain error 105 - Could not register the CGFont '<CGFont (0x7f8a9345fd60): MaterialIcons-Regular>')'
```

Doing some research, it was complaining because it was trying to register the font **again** for some reason by calling ```FontLoader.loadFont(fontName)``` twice for the same font. Basically, ```UIFont.fontNamesForFamilyName(fontName)``` is still empty after the first registration. 

I wasn't sure why it was not working for Material Icons, but my workaround was to call ```CTFontManagerUnregisterGraphicsFont``` prior to calling ```CTFontManagerRegisterGraphicsFont```, which is an ugly fix, but I didn't look into the problem deeper and needed to find quick fix.

Anyways, I'm not sure if this is only happening to me but wanted to raise the issue for anyone else facing similar problem.

Thank you

**Comment by mikeKickserv** [comment]
I see the same issue

**Comment by haydentrail** [comment]
I came across this issue too, it is due to the fact that the font family name is 'Material Icons' but the function iconFontOfSize looks for the font name 'MaterialIcons-Regular' in fontNamesForFamilyName.  This will always return zero.

UIFont.fontNamesForFamilyName('MaterialIcons-Regular').count == 0 

needs to change to...

UIFont.fontNamesForFamilyName('Material Icons').count == 0 

I suggest creating a new function to return the font family name for this function.  I hope this helps.
